# Generated by Django 2.1.7 on 2019-03-16 13:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(blank=True, help_text='Enter the META format for the data', max_length=200, unique=True, verbose_name='Meta Format')),
                ('data_file', models.FileField(help_text='Upload the file containing the datasets (.csv, .json, ...)', upload_to='data/', verbose_name='Data File')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', ckeditor.fields.RichTextField()),
                ('doc_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_gen.DocumentMeta')),
            ],
        ),
    ]
