# Generated by Django 2.1.7 on 2019-03-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(help_text='Upload the file containing the datasets (.csv, .json, ...)', upload_to='data/', verbose_name='Data File')),
            ],
        ),
        migrations.RemoveField(
            model_name='documentmeta',
            name='data_file',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_gen.DocumentMeta', verbose_name='Meta for document'),
        ),
    ]
