# Generated by Django 2.1.7 on 2019-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_gen', '0002_auto_20190316_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='name', max_length=50, verbose_name='Template Name'),
            preserve_default=False,
        ),
    ]
